### PR TITLE
Support .NET Framework versions providing RuntimeInformation

### LINKED ISSUE #264: RuntimeInformation package used also when not needed
Starting from version 4.7.1 the .NET Framework API includes the RuntimeInformation class, therefore the related package should not be referenced

### PR DESCRIPTION
**Pull request by snakefoot**
Closes #264

https://github.com/travis-ci/travis-ci/issues/4571#issuecomment-674551385

https://stu.dev/dotnet-framework-reference-assemblies-via-nuget

### CODE REVIEW

**Comment by cwigley** [comment]
Guessing that if your build changes go through they will solve for the mono dependency problem my builds are running up against.

**Comment by snakefoot** [comment]
@cwigley That was the plan. And can see net452 + net461 projects now compiles without help from FrameworkPathOverride.

Now trying to add net471 as targetframework.

**Comment by snakefoot** [comment]
Yes everything is green nuget-package with net471 on both AppVeyor and Travis

**Comment by luigiberrettini** [comment]
Supersedes #260

**Comment by snakefoot** [comment]
Maybe ready for release of ver. 6.0.2 ?

**Comment by luigiberrettini** [comment]
Not yet I was planning to change also the build scripts in 6.0.2

**Comment by luigiberrettini** [comment]
Version 6.0.2 has been released  🙂

**Pull request merged**
