### PR TITLE
SysLogTarget that inherits from AsyncTaskTarget

### PR DESCRIPTION
**Pull request by snakefoot**
No batching support. Only blocking/discarding throttle support. Adds timeout-support.

### CODE REVIEW

**Comment by luigiberrettini** [comment]
I feel confused because there are a lot of changes in this PR: tartget framework, dependencies, Socket implementation, inheriting from AsyncTaskTarget.

I prefer to have each PR keep features and address only one topic: in this way it is easier to isolate changes, to discuss and review them and to allow users understand the evolution of the library

**Comment by snakefoot** [comment]
Rolled off random improvements.

**Comment by luigiberrettini** [comment]
It could have been useful to collaborate on extracting the features implemented in the Syslog target to provide a base NLog tartget following TPL best practices and avoiding some pitfalls.

I am not sure I want to inherit from NLog AsyncTaskTarget since it has some similar features implemented in a different way and some other features are lacking.

**Comment by snakefoot** [comment]
Yes Syslog-Target has the ability to send out-of-order, and then expects that the timestamp/sequenceid will ensure that they will get stored in correct order at the receiver.
Unsure if many/anyone makes use of this feature. Having multiple SysLog-target within a RoundRobinGroup-Compound-Wrapper can also do this. 

What features in the SysLog-Target are you missing in the AsyncTaskTarget? If you have ideas for improving throttle/backoff/retry-strategy implementation, then I'm very interested. Unless you mean features for doing out-of-order-processing.

**Comment by luigiberrettini** [comment]
The usage of multiple parallel AsyncLoggers can potentially result in sending messages to the Syslog server out-of-order, but its main goal was to allow a huge amount of log messages to be dequeued.

I gave a quick look at the AsyncTaskTarget and it would be nice to have throttle or a more TPL oriented management of operations: I saw what feels a more or less manual handling of passing control from one task to the other, probably inspired by the original asyncContinuation

**Comment by snakefoot** [comment]
The internal queue in AsyncTaskTarget uses the lock-free ConcurrentQueue, and it is very fast and very concurrent. So logger-threads will not meet congestion.

There is a `TaskDelayMilliseconds`-property that delays the start of the next Task. But it is mostly intended to increase chance of batching (Send 50 LogEvents within a single buffer-send). What TPL oriented throttle operations do you find useful?

**Comment by luigiberrettini** [comment]
The throttle I implemented allows the user to choose the behavior when the queue is filling up.
A BlockingCollection is used to implement bounding/blocking.

Manually set delays, handling of timeout, using the Timer class or having batch operations doesn't fill natural to me in a TPL world: asynchronicity handles things when it is possible and we shouldn't worry to execute batches or orchestrate Tasks.

**Comment by snakefoot** [comment]
Well batching is the king, when you have one writer with high latency, that has to keep up with many logger-threads. 

The internal-queue used can be configured to be blocking, so when it is filled up then logger-threads will be blocked. What kind of behavior change are you thinking that should happen when the queue is filling up? Do you want the Logger-threads to sleep/spin/block when the internal-queue is close to be filled? Is that the TPL throttle oriented throttle-logic you mentioned?

**Comment by luigiberrettini** [comment]
I think it would be useful for user to configure what they want as with my throttling class.
This way you can block, discard, defer or do nothing when the consumers are slower than the producer.

If you have a queuing mechanism you do not need batches: the queue allows to process at the pace of the Target without an impact on the logging software since you are no more synchronous.

Moreover pay attention not to confuse threads with tasks: the impact on performance is way lower with the seconds and this is why they are so efficient.

For heavy load there should be the possibility of parallel processing within the same target since out-of-order delivery could be accepted.

Probably adding advanced retry policies could be implemented in the future, maybe relying on libraries like Polly.

For sure a lot of attention should be put in using Tasks based TPL or async/await, since it is really easy to add bugs without notice e.g. if you chain tasks by adding ContinueWith in a for, you run the risk of difficult to debug UnobservedTaskExceptions.

**Comment by snakefoot** [comment]
Right the internal-queue has the following overflow-actions:

- Block - Block until there's more room in the queue.
- Discard the overflowing item.
- Grow - Grow the queue.

So you are suggesting to add another action that makes the logging-thread throttle when getting close to overflow.

> If you have a queuing mechanism you do not need batches:

If you are sending HTTP-requests another computer and ACK-delay is 200 ms. Then it is best to send large chunks. But I guess SysLog relies on streaming data over TCP / UDP, where the TCP-stack helps out (takes care of the batching).

But it sounds like AsyncTaskTarget is not for the SysLog-target. Will close this PR.

**Pull request closed without merging**
