### PR TITLE
Use the Layout type for the message send server setting

### LINKED ISSUE #270: Message send server setting not rendered as expected
This is not working:

```json
"syslog": {
...
      "messageSend": {
          "protocol": "tcp",
          "tcp": {
            "server": "${configsetting:item=LoggingContext.SyslogUrl}"
...
```

See also: https://stackoverflow.com/questions/66730543/nlog-config-settings-renderer-not-working-as-expected

### PR DESCRIPTION
**Pull request by snakefoot**
Resolves #270

### CODE REVIEW

**Comment by snakefoot** [comment]
Closing and reopening, because of `macOS`-build timeout

**Comment by snakefoot** [comment]
@luigiberrettini Ready for review

**Comment by snakefoot** [comment]
@luigiberrettini Thank you for the merge.

**Comment by snakefoot** [comment]
@luigiberrettini How are the plans for releasing ver. 6.0.3 ?

**Comment by luigiberrettini** [comment]
It will be released when some more bugs are fixed: I would rather not use the release per PR model.

**Comment by snakefoot** [comment]
@luigiberrettini Any ETA for releasing ver. 6.0.3 ?

**Comment by luigiberrettini** [comment]
Not at the moment.

Please take also a look at the [Support section](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/master/docs/README.md#support) of the README.

Thanks!

**Pull request merged**
